### ISSUE TITLE
[FIX] Remove inline CSS from all the components

### ISSUE THREAD

**Issue by jatiinyadav** [jatiinyadav/Crew-Connect#14]
1. Remove inline CSS from all the components and create new class with proper names in `styles/common.css`
2. Remove the `styleURLs` property from every component and make sure that all the components are using css from `styles/common.css.`

**Comment by IP80808080** [comment]
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me? Additionally, could you please label it for the appropriate level? Thank you! 🚀

**Comment by jatiinyadav** [comment]
Hi @IP80808080,
Any updates?

**Comment by IP80808080** [comment]
I am working on it, I will share the updates tomorrow

**Comment by jatiinyadav** [comment]
Hi @IP80808080,
Still no updates.

**Comment by roshnimishraa** [comment]
Hi @jatiinyadav Please assign this issue to me
