### ISSUE TITLE
[FIX] Landing Page Responsive

### ISSUE THREAD

**Issue by jatiinyadav** [jatiinyadav/Crew-Connect#15]
![image](https://github.com/jatiinyadav/Crew-Connect/assets/73248007/daa67889-6add-420e-b00c-45dceb9cbcc7)

- Make the landing page responsive for all the screen sizes.
- Make sure to do the styling changes in `styles/common.css`

**Comment by IP80808080** [comment]
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me? Additionally, could you please label it for the appropriate level? Thank you! 🚀

**Comment by IP80808080** [comment]
Hello Sir
I have submitted a pull request for issue #4, which includes a video explanation for better understanding. I kindly request you to review the pull request.
Sir, I've encountered an issue while reviewing the output of my changes. After making adjustments and checking for responsiveness, I've noticed that the changes aren't immediately reflected. Is this a problem with my browser or IDE? Interestingly, upon reloading the page, the responsiveness updates are visible.

**Comment by jatiinyadav** [comment]
> Hello Sir I have submitted a pull request for issue #15, which includes a video explanation for better understanding. I kindly request you to review the pull request. Sir, I've encountered an issue while reviewing the output of my changes. After making adjustments and checking for responsiveness, I've noticed that the changes aren't immediately reflected. Is this a problem with my browser or IDE? Interestingly, upon reloading the page, the responsiveness updates are visible.

Hi, 
I am unable to view the video which you are taking about.

**Comment by IP80808080** [comment]
Oh sorry my bad, I have made the boiler answer for the future submission of Issues, and I forget to make change in this one

**Comment by jatiinyadav** [comment]
@IP80808080 Can you please add the video, so that I can review the PR.

**Comment by jatiinyadav** [comment]
@IP80808080 Any updates?

**Comment by IP80808080** [comment]
I will share the latest update today itself, my exams were going on, that's why it took me a while

**Comment by IP80808080** [comment]
Sir I have Removed the previous pull request since there was some changes required, and submitted a pull request for issue https://github.com/jatiinyadav/Crew-Connect/issues/15, which includes a video explanation for better understanding. I kindly request you to review the pull request

https://github.com/jatiinyadav/Crew-Connect/assets/94137507/735e1ec2-1807-42c2-b561-006e89a62040
