### ISSUE TITLE
[DOCS] Create a step-by-step installation docs with images

### ISSUE THREAD

**Issue by jatiinyadav** [jatiinyadav/Crew-Connect#17]
The context of images here means, while creating the docs make sure to only add images related to the installation of the project.

**Comment by pankildoshi** [comment]
Hello Jatin, I would love to contribute to this project and I want to get started. Can you assign this issue to me? Thank you.

**Comment by IP80808080** [comment]
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me? Thank you! 🚀
I have just now have created a beautiful Learn.md [Link](https://github.com/urstrulynishkarsh/ReactChat/blob/main/Learn.md) with Video as well

**Comment by jatiinyadav** [comment]
> 👋 Hello! I'd be happy to help with this issue. Could you please assign it to me? Thank you! 🚀 I have just now have created a beautiful Learn.md [Link](https://github.com/urstrulynishkarsh/ReactChat/blob/main/Learn.md) with Video as well

Thankyou for your interest.
But this issue is already assigned to @pankildoshi.

**Comment by pankildoshi** [comment]
Hi @jatiinyadav , I have raised the PR. Can you review it and also let me know if there are any changes required. Thank you!
