### ISSUE TITLE
[FIX] Fix MongoDB Change Stream

### ISSUE THREAD

**Issue by jatiinyadav** [jatiinyadav/Crew-Connect#20]
1. In the `MongoDLL` Class Library project I have created a Class as `MongoData.cs`, in that class I have implemented the Mongo DB change stream, but it is not working correctly. Line 53

![image](https://github.com/jatiinyadav/Crew-Connect/assets/73248007/96712a88-1eff-4720-b751-508d8b74192e)

2. When a user sends a message from the frontend, for now the message is being directly added into the array of messages, But I want that the message should be added by the data that is passed by the MongoDB change stream.

If you have any doubts, feel free to ask in the comments.

**Comment by Shirapti-nath** [comment]
id like to work on this project sir. Can you assign me a task

**Comment by Shweta-281** [comment]
I want to work on this issue . Please assign me.

**Comment by jatiinyadav** [comment]
Hi @Shirapti-nath, as you didn't responded since last one week, this issue is being reassigned to @Shweta-281.

**Comment by jatiinyadav** [comment]
Hi @Shweta-281,
Any updates?
