### ISSUE TITLE
Able to react to other people messages

### ISSUE THREAD

**Issue by Chelseasingla1** [jatiinyadav/Crew-Connect#24]
**Is your feature request related to a problem? Please describe.**
There is no feature of reacting to other messages.

**Describe the solution you'd like**
I would like to add feature where one can react to other messages through emojis or notes.

**Describe alternatives you've considered**

**Additional context**
Please assign me this issue under GSSoC'24

**Comment by jatiinyadav** [comment]
Hi @Chelseasingla1,

It's a great feature. Please make sure you are storing the reactions in DB as well.

**Comment by Chelseasingla1** [comment]
> Hi @Chelseasingla1,
> 
> It's a great feature. Please make sure you are storing the reactions in DB as well.

@jatiinyadav yes sure i will try my best Thankyou!!

**Comment by jatiinyadav** [comment]
Hi @Chelseasingla1,
Any updates?
