### ISSUE TITLE
Voice Notes

### ISSUE THREAD

**Issue by Chelseasingla1** [jatiinyadav/Crew-Connect#25]
**Is your feature request related to a problem? Please describe.**
No feature of sending voice notes

**Describe the solution you'd like**
I would like to add feature where crew mates can send voice notes to each other.

**Describe alternatives you've considered**

**Additional context**
Please assign me this issue under GSSoC'24.

**Comment by Chelseasingla1** [comment]
Thanks for assigning!!

**Comment by jatiinyadav** [comment]
Hi @Chelseasingla1,
Any updates?

**Comment by Chelseasingla1** [comment]
> Hi @Chelseasingla1, Any updates?

yes  i will update it by today

**Comment by Chelseasingla1** [comment]
> Hi @Chelseasingla1, Any updates?

There is still some issue with voice notes function like how it will reach to another server maybe need some changes regarding that can you provide me some time for that, it is showing recording is on but not able to sent it in recording from
