### ISSUE TITLE
[BUG] Navigate to the bottom of the chat

### ISSUE THREAD

**Issue by jatiinyadav** [jatiinyadav/Crew-Connect#29]
Chat should be scrolled at the bottom in following cases.

1. When a user login's in the group
2. After login, if the user scrolls above in the chat and if sends a message.

**Comment by anglerfishlyy** [comment]
Hey , can you  assign me this?

**Comment by Shweta-281** [comment]
I also want to part of this project. Please assign me.

**Comment by jatiinyadav** [comment]
Hi @Shweta-281,
Thank you for your interest.
This issue is being currently assigned to @anglerfishlyy. Please wait for a couple of days. 
In the mean-time you can view our existing issues [here](https://github.com/jatiinyadav/Crew-Connect/issues).

**Comment by jatiinyadav** [comment]
Hi @anglerfishlyy,
Any updates?

**Comment by roshnimishraa** [comment]
Hi @jatiinyadav Please assign this issue to me
