### ISSUE TITLE
[FEAT] User can join multiple groups

### ISSUE THREAD

**Issue by jatiinyadav** [jatiinyadav/Crew-Connect#30]
1. A user can join multiple groups and the notifications of all the groups should be in real time and user should be notified about the message.
2. If the user clicks on the notification of the new message, user's chat should be of that group.

If you have any doubts, feel free to ask in comments.

**Comment by anglerfishlyy** [comment]
Could you assign me this?

**Comment by rickon43** [comment]
i have some design ideas

**Comment by jatiinyadav** [comment]
Hi @anglerfishlyy,
Any updates?
