### ISSUE TITLE
[FEAT] Unique Code Generation for New Chat Groups

### ISSUE THREAD

**Issue by jatiinyadav** [jatiinyadav/Crew-Connect#31]
1. Generate unique alphanumeric codes of 5-6 characters for each new chat group.
2. Ensure that the generated codes are unique across all existing groups.
3. Consider scalability and performance implications, especially as the number of groups grows.
4. Integrate the code generation logic into the process of creating new chat groups.
5. There should be a new input when a user is joining a group. A user can join a group by entering group name or unique code.
6. There should be a option for the Admin to copy the group name or unique code.

If you have any doubts, feel free to ask in comments.

**Comment by pankildoshi** [comment]
Hi @jatiinyadav , I would like to work on this issue. Can you assignee it to me ?

**Comment by jatiinyadav** [comment]
Hi @pankildoshi,
Any updates?

**Comment by pankildoshi** [comment]
Hi @jatiinyadav ,
Yes, I have created Seevice for creating Unique code and I have updated Create and Join group methods accordingly.

On UI side I'm thinking, once user creates the room they should see a pop up/modal for room code with copy button. Also code can be copied from chat room. Currently working on UI part.

If you have any suggestions or specifics please let me know. I'll try to close this as soon as possible.

**Comment by jatiinyadav** [comment]
Instead of a showing a pop up you can create 2 buttons, something like this:

![image](https://github.com/jatiinyadav/Crew-Connect/assets/73248007/62638092-f9d3-4dc5-8dbc-312e4bb06fab)

**Comment by pankildoshi** [comment]
Okay @jatiinyadav , Instead of popup, I'll keep two buttons like these.

But Does that mean We want to allow users to join Room with Group Code as well as Group Name? Can you clarify this for me?

**Comment by jatiinyadav** [comment]
> Okay @jatiinyadav , Instead of popup, I'll keep two buttons like these.
> 
> But Does that mean We want to allow users to join Room with Group Code as well as Group Name? Can you clarify this for me?

Yes
