### ISSUE TITLE
[FEAT] Add a regex pattern

### ISSUE THREAD

**Issue by jatiinyadav** [jatiinyadav/Crew-Connect#32]
1. Add a regex pattern for email validation in both the cases: When creating a group or joining a group.
2. Use the existing Toast Message NPM Package for appropriate errors.

**Comment by SiddhantBarman-PageUp** [comment]
hey @jatiinyadav please assign this issue to me under gssoc 2024.
problem:
while creating room and entering admin email there is only require field is added no regax pattern for proper validation.
solution: 
adding a regax pattern for proper validation and show toast if email is not valid.

**Comment by jatiinyadav** [comment]
Hi @SiddhantBarman-PageUp,
Any updates?
