### ISSUE TITLE
I want to work on UI of the website.

### ISSUE THREAD

**Issue by MehtabAsHellic** [jatiinyadav/Crew-Connect#35]
Hi Admin,

I'm interested in contributing to your project as part of GSSoC. I've been following your work and believe my skills align well. You can find my portfolio here: (https://sites.google.com/view/uibymehtab) and LinkedIn (https://www.linkedin.com/in/mehtabarkhan/)

Thanks,
Mehtab

**Comment by jatiinyadav** [comment]
Hi @MehtabAsHellic,
You can please specify little bit more about the UI design?

Like What have you planned? Which components you will work on?

**Comment by MehtabAsHellic** [comment]
> Hi @MehtabAsHellic, Can you please specify a little bit more about the UI design?
> 
> Like What have you planned? Which components you will work on?

So i was thinking to redesign the landing page, login/signup/ chat design for the crew connect.
A new logo and new branding according to the theme of the branding I will design the UI of the crew connect.

any design style you would like to describe or have in your mind ? As i was thinking to make into my style, please let me know your words too @jatiinyadav

**Comment by jatiinyadav** [comment]
As of know I didn't had any plans on changing the UI, But I hope you will make the UI better than the existing one.

**Comment by MehtabAsHellic** [comment]
> As of know I didn't had any plans on changing the UI, But I hope you will make the UI better than the existing one.

ok

**Comment by MehtabAsHellic** [comment]
hey @jatiinyadav is there any link for this project ?

**Comment by jatiinyadav** [comment]
> hey @jatiinyadav is there any link for this project ? apart of that loom video

Currently, I haven't deployed this project.

**Comment by MehtabAsHellic** [comment]
> > hey @jatiinyadav is there any link for this project ? apart of that loom video
> 
> Currently, I haven't deployed this project.

ok

**Comment by MehtabAsHellic** [comment]
hey @jatiinyadav I am starting the design of UI for cewconnect
