### ISSUE TITLE
Designing a logo for CrewConnect 

### ISSUE THREAD

**Issue by MehtabAsHellic** [jatiinyadav/Crew-Connect#44]
I want to design a logo and brand identity before going into the UI design. As i am being designing the UI for the project.

It will be great to design a logo first and got your view.

**Comment by jatiinyadav** [comment]
Hi @MehtabAsHellic, 
The logo looks good, can you please change the colour code?

**Comment by MehtabAsHellic** [comment]
> Hi @MehtabAsHellic, The logo looks good, can you please change the colour code?

sure as I kept this because blue define team and believe and yellow define connection.
any suggestion of your, as I will provide you some color sample too.

**Comment by MehtabAsHellic** [comment]
> > > Hi @MehtabAsHellic, The logo looks good, can you please change the colour code?
> > 
> > 
> > sure as I kept this because blue define team and believe and yellow define connection. any suggestion of your, as I will provide you some color sample too.
> 
> TBH, I'm not that good with colour palettes. I would be prefer something not too bright nor too dull, something mediocre

ok

**Comment by MehtabAsHellic** [comment]
![NewCoption1](https://github.com/jatiinyadav/Crew-Connect/assets/101495398/16ea5bf5-4e94-4eae-9dba-29913f5a6afd)
![Newcoption2](https://github.com/jatiinyadav/Crew-Connect/assets/101495398/763d0c05-b40b-4eaf-b226-9f77a9aba009)

**@jatiinyadav Let me know your thought here.**

**Comment by jatiinyadav** [comment]
Yes, this one looks good.

**Comment by MehtabAsHellic** [comment]
> Yes, this one looks good.

Thank you @jatiinyadav 

I will put the both svg format in the frontend/src section of the repository and PR.

**Comment by MehtabAsHellic** [comment]
please check and confirm
https://github.com/jatiinyadav/Crew-Connect/pull/47
