### ISSUE TITLE
[DOC] Update Readme file for contribution git commands

### ISSUE THREAD

**Issue by Amruta7203** [jatiinyadav/Crew-Connect#46]
The current readme.md file does not contain git commands required for contribution i.e from forking a repo to pull requests.

I propose adding all the git commands in the readme file.

**Comment by jatiinyadav** [comment]
Hi @Amruta7203,
Git Commands are present in [CONTRIBUTING.md](https://github.com/jatiinyadav/Crew-Connect/blob/master/CONTRIBUTING.md)

**Comment by Amruta7203** [comment]
Oh I didn't' notice. Thanks for the reply.
