### ISSUE TITLE
📝[Docs]: Add Table of Contents to README file.

### ISSUE THREAD

**Issue by GUNJESH843** [jatiinyadav/Crew-Connect#50]
**What Docs changes are you proposing?**
I am proposing the addition of a Table of Contents to the README file. The Table of Contents will include links to key sections such as Usage, Screenshots, Features, Setup Instructions, Contributing, Documentation, Join Us, and Our Contributors.

**Why do the Docs need this improvement? What is the motivation for this change? How will this change benefit the community?**
The documentation will benefit from this improvement by providing users with an easy-to-navigate structure. This change will enhance the user experience by allowing users to quickly locate and access relevant sections of the README. The motivation behind this change is to improve the overall readability and usability of the documentation, making it more professional and user-friendly.

**Describe the solution you'd like**
The solution involves inserting a Table of Contents at the beginning of the README file. This Table of Contents will contain anchor links to the following sections
- Introduction
- tech Stack
- Project Demonstration
- Contributing
- Contact

**Describe alternatives you've considered**
An alternative approach considered was to include a sidebar or a collapsible menu for navigation within the README. However, these methods may not be as straightforward to implement in a Markdown file and might reduce the simplicity and compatibility of the document across different viewers.

**Additional context**
Adding a Table of Contents will make the documentation more organized and accessible, especially for first-time users. Below is an example of how the Table of Contents will look.
![Screenshot 2024-06-06 213549](https://github.com/jatiinyadav/Crew-Connect/assets/109446288/01ec6b17-d394-4ada-a216-d8dc64fa2be9)

**Comment by GUNJESH843** [comment]
@jatiinyadav can you assign this issue to me.

**I AM A GSSOC CONTRIBUTER**

Thankyou.

**Comment by jatiinyadav** [comment]
Hi @GUNJESH843,
Make sure you add Table of Contents in all the md files, not specifically README.md

**Comment by jatiinyadav** [comment]
Hi @GUNJESH843, 
Updating only README.md file will not be counted as `LEVEL 1` issue.
Please update all the MD files otherwise I have to mark the ticket as `LEVEL 0`.

There are strict guidelines from the GSSOC Program Managers.

**Comment by GUNJESH843** [comment]
@jatiinyadav sure

**Comment by GUNJESH843** [comment]
@jatiinyadav Hey, I have worked on the .md files mentioned by you and have added the table of contents to 4 files
1. README.md
2. CODE_OF_CONDUCT.md 
3. CONTRIBUTING.md
4. INSTALLATION.md

I request to label this as  >= level 2, this would help motivate me to work more on such issues, 

Thank you
