### ISSUE TITLE
Generate shareable QR or link

### ISSUE THREAD

**Issue by sanskriti-lal** [jatiinyadav/Crew-Connect#56]
**Is your feature request related to a problem? Please describe.**
users often encounter difficulties in sharing and accessing chat rooms efficiently, leading to communication barriers and delays in collaboration. Manually sharing URLs or invite codes can be cumbersome and prone to errors, especially when dealing with multiple participants or frequent room access. This process can result in frustration, miscommunication, and decreased productivity for users who rely on seamless and quick access to chat rooms for effective communication and collaboration.

**Describe the solution you'd like**
Integrating either QR code generation or a shareable link into your platform can significantly enhance user experience and streamline communication within chat rooms.

After creating a chat room, users should have the ability to generate a QR code or link for easy sharing and access. Once the chat room is set up, a "Generate QR Code or link" button will be prominently displayed within the chat interface. When the user clicks this button, the system will create a unique QR code/link that encapsulates the chat room's URL or identifier. This QR code/link can then be displayed in a modal or popup, allowing users to scan it with their mobile devices. Additionally, users will have the option to share the QR code/link via email, social media, or other messaging platforms, ensuring that team members or participants can join the chat room effortlessly by simply scanning the code with their device's camera. This process streamlines the way users can invite others to join the chat room, eliminating the need for manual link sharing and providing a more efficient and user-friendly experience.

**Describe alternatives you've considered**
Unique Room Identifiers: Instead of relying on traditional URLs or generic invite codes, each chat room can be assigned a unique identifier or token. Users can share this identifier with others, who can then input it directly into the chat platform to gain access. This method simplifies the sharing process and reduces the risk of unauthorized access, as the identifiers are specific to each chat room instance.

**Additional context**
I'm a GSSoC'24 contributor, with a strong understanding of web development and I want to work on this project.
I can add the generate QR or shareable link option as per your wish. I can even try to integrate both.
so can you please assign it to me @jatiinyadav

**Comment by jatiinyadav** [comment]
Hi @sanskriti-lal, 
Go ahead, please create both (QR Code and shareable link)
All the best 🚀
